# Generated by Django 4.1.7 on 2023-03-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_performer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='created_by',
        ),
    ]
