# Generated by Django 4.1.7 on 2023-03-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_performer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='in_favorites',
        ),
    ]
