# Generated by Django 4.1.7 on 2023-02-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_title',
            new_name='title',
        ),
    ]
