# Generated by Django 4.1.7 on 2023-02-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtrack',
            name='track_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
