# Generated by Django 4.1.7 on 2023-03-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_albumtrack_track_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
    ]
